name: CI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  static-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: pnpm/action-setup@v2.2.2
        with:
          version: 8
      - uses: actions/setup-node@v2
        with:
          node-version: 18
          cache: "pnpm"
      - run: pnpm i
      - run: cd examples && pnpm i
      - run: pnpm check:lint
      - run: pnpm check:types
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: pnpm/action-setup@v2.2.2
        with:
          version: 8
      - uses: actions/setup-node@v2
        with:
          node-version: 18
          cache: "pnpm"
      - run: pnpm i
      - run: pnpm test
